# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  java-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B -Dmaven.test.skip=true package --file pom.xml

      - name: Temporarily save jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: jar-artifact
          path: ${{ github.workspace }}/target/midas-app-0.0.1-SNAPSHOT.jar

  docker-build:
      runs-on: ubuntu-latest
      needs: [java-build]
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v3
        - uses: rlespinasse/github-slug-action@v3.x
        - uses: docker/setup-buildx-action@v2
        - uses: actions/download-artifact@v2
          with:
            name: jar-artifact
            path: target/

        - name: Login to GHCR
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: build and push docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: Dockerfile
            push: true
            tags: ghcr.io/midas-tec/midas-app:${{env.GITHUB_REF_SLUG}}
            cache-from: type=registry,ref=ghcr.io/midas-tec/midas-app:${{env.GITHUB_REF_SLUG}}_cache
            cache-to: type=registry,ref=ghcr.io/midas-tec/midas-app:${{env.GITHUB_REF_SLUG}}_cach,mode=max


